// template-5/src/components/sections/HeroSection.tsx
'use client';

import { motion } from 'motion/react';
import Particles from '@/components/ui/particles';
import BlurText from '@/components/ui/blur-text';
import ErrorBoundary from '@/components/ui/error-boundary';
import GithubIcon from '@/icons/github-icon';
import LinkedinIcon from '@/icons/linkedin-icon';
import TwitterXIcon from '@/icons/twitter-x-icon';
import InstagramIcon from '@/icons/instagram-icon';
import DiscordIcon from '@/icons/discord-icon';
import FacebookIcon from '@/icons/facebook-icon';
import BrandThreadsIcon from '@/icons/brand-threads-icon';
import YoutubeIcon from '@/icons/youtube-icon';
import TiktokIcon from '@/icons/tiktok-icon';
import RedditIcon from '@/icons/reddit-icon';
import { ArrowDown } from 'lucide-react';

export default function HeroSection() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
      <Particles
        backgroundColor="#0a0a0a"
        particleColor="#22c55e"
        particleCount={600}
        radius={1.2}
        particleSpeed={1.2}
        scale={0.0008}
        cellSize={25}
      />

      <div className="relative z-10 text-center px-6 max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6 }}
        >
          <ErrorBoundary>
            <motion.p
              className="text-primary text-sm font-[family-name:var(--font-jetbrains)] tracking-widest uppercase mb-4"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
            >
              Computer Science Student &amp; Full-Stack Developer
            </motion.p>
          </ErrorBoundary>

          <ErrorBoundary>
            <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight mb-6">
              <BlurText
                text="Hi, I'm "
                animateBy="letters"
                direction="top"
                delay={80}
                stepDuration={0.4}
                className="inline text-foreground font-[family-name:var(--font-display)]"
              />
              <BlurText
                text="Saadi"
                animateBy="letters"
                direction="top"
                delay={80}
                stepDuration={0.4}
                className="inline text-primary font-[family-name:var(--font-display)] bg-gradient-to-r from-primary to-emerald-300 bg-clip-text"
              />
            </h1>
          </ErrorBoundary>

          <ErrorBoundary>
            <motion.p
              className="text-muted-foreground text-lg md:text-xl max-w-2xl mx-auto mb-8 leading-relaxed"
              initial={{ opacity: 0, y: 20, filter: 'blur(8px)' }}
              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              transition={{ delay: 0.8, duration: 0.8, ease: [0.25, 0.46, 0.45, 0.94] }}
            >
              Building intelligent software, full-stack web apps, and AI-powered
              solutions through clean, practical code.
            </motion.p>
          </ErrorBoundary>

          <ErrorBoundary>
            <motion.div
              className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-12"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.0, duration: 0.8 }}
            >
              <motion.a
                href="#projects"
                className="group relative inline-flex items-center justify-center gap-2 h-11 rounded-lg px-8 text-sm font-medium bg-primary text-primary-foreground shadow-lg shadow-primary/25 overflow-hidden"
                whileHover={{ scale: 1.03, y: -1 }}
                whileTap={{ scale: 0.98 }}
              >
                <span className="absolute inset-0 bg-gradient-to-r from-primary/0 via-white/10 to-primary/0 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-700" />
                <span className="relative z-10">View My Work</span>
              </motion.a>
              <motion.a
                href="#contact"
                className="inline-flex items-center justify-center gap-2 h-11 rounded-lg px-8 text-sm font-medium border border-border bg-background/50 backdrop-blur-sm shadow-sm hover:bg-accent hover:text-accent-foreground transition-colors"
                whileHover={{ scale: 1.03, y: -1 }}
                whileTap={{ scale: 0.98 }}
              >
                Get In Touch
              </motion.a>
            </motion.div>
          </ErrorBoundary>

          <ErrorBoundary>
            <motion.div
              className="flex items-center justify-center gap-5"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.2, duration: 0.8 }}
            >
              {[
                { icon: GithubIcon, href: 'https://github.com/saadisafdar', label: 'GitHub' },
                { icon: LinkedinIcon, href: 'https://www.linkedin.com/in/saadisafdar/', label: 'LinkedIn' },
                { icon: TwitterXIcon, href: 'https://x.com/saadisafder', label: 'X' },
                { icon: InstagramIcon, href: 'https://www.instagram.com/saadisafdar/', label: 'Instagram' },
                { icon: DiscordIcon, href: 'https://discord.com/users/saadisafdar', label: 'Discord' },
                { icon: FacebookIcon, href: 'https://www.facebook.com/saadisafdar1', label: 'Facebook' },
                { icon: BrandThreadsIcon, href: 'https://www.threads.com/@saadisafdar', label: 'Threads' },
                { icon: YoutubeIcon, href: 'https://www.youtube.com/@Fur_And_Funny', label: 'YouTube' },
                { icon: TiktokIcon, href: 'https://www.tiktok.com/@saadisafdar', label: 'TikTok' },
                { icon: RedditIcon, href: 'https://www.reddit.com/user/Efficient-Word1384/', label: 'Reddit' },
              ].map((social, i) => (
                <motion.a
                  key={social.label}
                  href={social.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 1.4 + i * 0.1 }}
                  whileHover={{ scale: 1.2, y: -3 }}
                  whileTap={{ scale: 0.9 }}
                >
                  <social.icon size={22} color="#a1a1aa" />
                </motion.a>
              ))}
            </motion.div>
          </ErrorBoundary>
        </motion.div>
      </div>

      <motion.a
        href="#about"
        className="absolute bottom-8 left-1/2 -translate-x-1/2 text-muted-foreground hover:text-primary transition-colors"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 2 }}
      >
        <motion.div
          animate={{ y: [0, 8, 0] }}
          transition={{ repeat: Infinity, duration: 2, ease: 'easeInOut' }}
        >
          <ArrowDown size={24} />
        </motion.div>
      </motion.a>
    </section>
  );
}

// template-5/src/components/HeroSection.vue
<template>
  <section class="hero-section">
    <!-- Particle canvas -->
    <canvas ref="canvasRef" class="hero-canvas" aria-hidden="true" />

    <!-- Content -->
    <div class="hero-content">
      <!-- Subtitle -->
      <p class="hero-subtitle anim-fade-in-up delay-200">
        Computer Science Student &amp; Full-Stack Developer
      </p>

      <!-- Heading -->
      <h1 class="hero-heading font-display" aria-label="Hi, I'm Saadi">
        <span class="hero-heading-plain">
          <span
            v-for="(ch, i) in hiChars"
            :key="'hi-' + i"
            class="hero-letter"
            :style="{ animationDelay: `${0.3 + i * 0.06}s` }"
          >{{ ch === ' ' ? '\u00a0' : ch }}</span>
        </span><span class="hero-heading-name">
          <span
            v-for="(ch, i) in nameChars"
            :key="'name-' + i"
            class="hero-letter hero-letter--green"
            :style="{ animationDelay: `${0.3 + (hiChars.length + 1 + i) * 0.06}s` }"
          >{{ ch }}</span>
        </span>
      </h1>

      <!-- Tagline -->
      <p class="hero-tagline anim-fade-in-up delay-900">
        Building intelligent software, full-stack web apps, and AI-powered
        solutions through clean, practical code.
      </p>

      <!-- CTA buttons -->
      <div class="hero-ctas anim-fade-in-up delay-1000">
        <a href="#projects" class="btn-primary" @click.prevent="smoothScroll('#projects')">
          View My Work
        </a>
        <a href="#contact" class="btn-outline" @click.prevent="smoothScroll('#contact')">
          Get In Touch
        </a>
      </div>

      <!-- Social links -->
      <div class="hero-socials anim-fade-in delay-1200">
        <a
          v-for="social in socialLinks"
          :key="social.label"
          :href="social.href"
          :title="social.label"
          class="social-link"
          target="_blank"
          rel="noopener noreferrer"
        >
          <SocialIcon :icon="social.icon" :size="22" />
        </a>
      </div>
    </div>

    <!-- Scroll arrow -->
    <a href="#about" class="scroll-arrow anim-fade-in delay-2000" @click.prevent="smoothScroll('#about')">
      <v-icon icon="mdi-chevron-down" size="28" class="anim-bounce-y" />
    </a>
  </section>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { socialLinks } from '@/data/portfolio.js'
import SocialIcon from '@/components/SocialIcon.vue'

const hiChars   = "Hi, I'm".split('')
const nameChars = "Saadi".split('')

const canvasRef = ref(null)
let animFrame = null

function smoothScroll(href) {
  const id = href.replace('#', '')
  document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' })
}

/* ── Particle system ── */
function initParticles(canvas) {
  const ctx = canvas.getContext('2d')
  let W = 0, H = 0
  let particles = []

  function resize() {
    W = canvas.width  = canvas.offsetWidth
    H = canvas.height = canvas.offsetHeight
  }

  function createParticle() {
    return {
      x: Math.random() * W,
      y: Math.random() * H,
      vx: (Math.random() - 0.5) * 0.6,
      vy: (Math.random() - 0.5) * 0.6,
      r: Math.random() * 1.2 + 0.3,
      alpha: Math.random() * 0.5 + 0.15,
    }
  }

  function reset() {
    particles = Array.from({ length: 500 }, createParticle)
  }

  function draw() {
    ctx.clearRect(0, 0, W, H)
    for (const p of particles) {
      p.x += p.vx
      p.y += p.vy
      if (p.x < 0) p.x = W
      if (p.x > W) p.x = 0
      if (p.y < 0) p.y = H
      if (p.y > H) p.y = 0
      ctx.beginPath()
      ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2)
      ctx.fillStyle = `rgba(34,197,94,${p.alpha})`
      ctx.fill()
    }
    animFrame = requestAnimationFrame(draw)
  }

  const ro = new ResizeObserver(() => { resize(); reset() })
  ro.observe(canvas)
  resize()
  reset()
  draw()
  return () => { ro.disconnect(); cancelAnimationFrame(animFrame) }
}

let cleanup = null
onMounted(() => { if (canvasRef.value) cleanup = initParticles(canvasRef.value) })
onUnmounted(() => cleanup?.())
</script>

<style scoped>
.hero-section {
  position: relative;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  background: #0a0a0a;
}

.hero-canvas {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
}

.hero-content {
  position: relative;
  z-index: 2;
  text-align: center;
  padding: 0 24px;
  max-width: 896px;
  margin: 0 auto;
}

.hero-subtitle {
  font-family: 'JetBrains Mono', monospace;
  font-size: 0.8125rem;
  letter-spacing: 0.15em;
  text-transform: uppercase;
  color: #22c55e;
  margin-bottom: 20px;
}

.hero-heading {
  font-size: clamp(3rem, 10vw, 6rem);
  font-weight: 400;
  line-height: 1.0;
  margin-bottom: 24px;
  letter-spacing: -0.02em;
}

.hero-heading-plain {
  color: #f4f4f5;
}

.hero-heading-name {
  /* word gap — margin-left adds the space between "I'm" and "Saadi" */
  margin-left: 0.28em;
}

/* Each green letter gets an explicit solid color so the animation
   (fadeInBlur with opacity:0 → 1) works correctly.
   background-clip:text on a parent does NOT affect display:inline-block children. */
.hero-letter--green {
  color: #22c55e;
}

.hero-tagline {
  font-size: clamp(1rem, 2.5vw, 1.2rem);
  color: #71717a;
  line-height: 1.7;
  max-width: 600px;
  margin: 0 auto 36px;
}

.hero-ctas {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 16px;
  flex-wrap: wrap;
  margin-bottom: 44px;
}

.hero-socials {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 4px;
  flex-wrap: wrap;
}

.scroll-arrow {
  position: absolute;
  bottom: 32px;
  left: 50%;
  transform: translateX(-50%);
  color: #52525b;
  text-decoration: none;
  transition: color 0.2s;
  z-index: 2;
}
.scroll-arrow:hover { color: #22c55e; }
</style>
