// template-5/src/components/sections/ProjectsSection.tsx
'use client';

import { motion } from 'motion/react';
import ScrollReveal from '@/components/ui/scroll-reveal';
import ErrorBoundary from '@/components/ui/error-boundary';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Github, Star } from 'lucide-react';
import portfolioData from '@/data/portfolio.json';

export default function ProjectsSection() {
  return (
    <section id="projects" className="py-24 px-6 relative">
      <div className="max-w-6xl mx-auto">
        <ErrorBoundary>
          <ScrollReveal direction="up">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Featured <span className="text-primary">Projects</span>
            </h2>
            <div className="w-16 h-1 bg-primary rounded-full mb-8" />
          </ScrollReveal>
        </ErrorBoundary>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {portfolioData.projects.map((project, i) => (
            <ErrorBoundary key={project.id}>
              <ScrollReveal direction="up" delay={0.1 * i}>
                <motion.div
                  whileHover={{ y: -6, scale: 1.01 }}
                  transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                >
                  <Card className="group h-full border-border/50 bg-card/50 backdrop-blur-sm hover:border-primary/50 transition-all duration-300 hover:shadow-xl hover:shadow-primary/10 relative overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                    <CardContent className="p-6 flex flex-col h-full relative z-10">
                      <div className="flex items-start justify-between mb-3">
                        <div className="flex items-center gap-2">
                          <span className="text-primary font-mono text-sm">
                            {String(project.id).padStart(2, '0')}
                          </span>
                          {project.featured && (
                            <motion.span
                              animate={{ rotate: [0, 15, -15, 0] }}
                              transition={{ repeat: Infinity, duration: 3, ease: 'easeInOut' }}
                            >
                              <Star size={14} className="text-yellow-500 fill-yellow-500" />
                            </motion.span>
                          )}
                        </div>
                        <Badge variant="outline" className="text-xs group-hover:border-primary/50 transition-colors">
                          {project.category}
                        </Badge>
                      </div>

                      <h3 className="text-xl font-semibold mb-2 group-hover:text-primary transition-colors">
                        {project.title}
                      </h3>

                      <p className="text-muted-foreground text-sm leading-relaxed mb-4 flex-1">
                        {project.description}
                      </p>

                      <div className="flex flex-wrap gap-1.5 mb-4">
                        {project.tags.map((tag) => (
                          <Badge
                            key={tag}
                            variant="secondary"
                            className="text-[10px] px-2 py-0.5 group-hover:bg-primary/10 group-hover:text-primary/80 transition-all"
                          >
                            {tag}
                          </Badge>
                        ))}
                      </div>

                      <motion.a
                        href={project.github}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center justify-center gap-2 h-8 rounded-md px-3 text-xs font-medium border border-input bg-background shadow-sm hover:bg-primary hover:text-primary-foreground transition-all duration-300"
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                      >
                        <Github size={14} />
                        Code
                      </motion.a>
                    </CardContent>
                  </Card>
                </motion.div>
              </ScrollReveal>
            </ErrorBoundary>
          ))}
        </div>
      </div>
    </section>
  );
}

// template-5/src/components/ProjectsSection.vue
<template>
  <section id="projects" class="section">
    <div class="section-inner">
      <!-- Heading -->
      <div ref="headingRef" class="reveal">
        <SectionHeading first-word="Featured" second-word="Projects" />
      </div>

      <!-- Grid -->
      <div class="projects-grid">
        <div
          v-for="(project, i) in portfolio.projects"
          :key="project.id"
          class="reveal portfolio-card project-card"
          :style="{ transitionDelay: `${i * 0.08}s` }"
          :ref="el => cardRefs[i] = el"
        >
          <!-- Hover gradient overlay -->
          <div class="project-overlay" />

          <div class="project-body">
            <!-- Top row: number + featured star + category -->
            <div class="project-top">
              <div class="project-meta-left">
                <span class="project-num font-mono">{{ String(project.id).padStart(2, '0') }}</span>
                <span v-if="project.featured" class="star-wiggle" title="Featured">⭐</span>
              </div>
              <span class="project-category">{{ project.category }}</span>
            </div>

            <!-- Title -->
            <h3 class="project-title">{{ project.title }}</h3>

            <!-- Description -->
            <p class="project-desc">{{ project.description }}</p>

            <!-- Tags -->
            <div class="project-tags">
              <span v-for="tag in project.tags" :key="tag" class="skill-chip skill-chip--xs">{{ tag }}</span>
            </div>

            <!-- GitHub link -->
            <a
              :href="project.github"
              class="project-link"
              target="_blank"
              rel="noopener noreferrer"
            >
              <v-icon icon="mdi-github" size="15" />
              Code
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { portfolio } from '@/data/portfolio.js'
import SectionHeading from '@/components/SectionHeading.vue'

const headingRef = ref(null)
const cardRefs   = ref([])

onMounted(() => {
  const observer = new IntersectionObserver(
    entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target) } }),
    { threshold: 0.1 }
  )
  ;[headingRef.value, ...cardRefs.value].filter(Boolean).forEach(el => observer.observe(el))
})
</script>

<style scoped>
.projects-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 24px;
}

@media (max-width: 900px) { .projects-grid { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 600px) { .projects-grid { grid-template-columns: 1fr; } }

.project-card {
  position: relative;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.project-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, rgba(34,197,94,0.05), transparent);
  opacity: 0;
  transition: opacity 0.4s;
  pointer-events: none;
  border-radius: 12px;
}
.project-card:hover .project-overlay { opacity: 1; }

.project-body {
  position: relative;
  z-index: 1;
  display: flex;
  flex-direction: column;
  height: 100%;
  padding: 24px;
}

.project-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.project-meta-left {
  display: flex;
  align-items: center;
  gap: 6px;
}

.project-num {
  font-family: 'JetBrains Mono', monospace;
  font-size: 0.875rem;
  color: #22c55e;
}

.project-category {
  font-size: 0.75rem;
  padding: 3px 10px;
  border-radius: 9999px;
  border: 1px solid rgba(255,255,255,0.1);
  color: #a1a1aa;
  transition: border-color 0.2s;
}
.project-card:hover .project-category { border-color: rgba(34,197,94,0.4); }

.project-title {
  font-size: 1.125rem;
  font-weight: 700;
  color: #f4f4f5;
  margin-bottom: 10px;
  transition: color 0.2s;
}
.project-card:hover .project-title { color: #22c55e; }

.project-desc {
  font-size: 0.875rem;
  color: #71717a;
  line-height: 1.65;
  margin-bottom: 16px;
  flex: 1;
}

.project-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-bottom: 18px;
}

.skill-chip--xs {
  font-size: 0.65rem;
  padding: 2px 8px;
}

.project-link {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 32px;
  padding: 0 14px;
  border-radius: 6px;
  font-size: 0.75rem;
  font-weight: 500;
  color: #a1a1aa;
  border: 1px solid rgba(255,255,255,0.1);
  text-decoration: none;
  width: fit-content;
  transition: background 0.2s, color 0.2s, border-color 0.2s;
}

.project-link:hover {
  background: #22c55e;
  color: #0a0a0a;
  border-color: #22c55e;
}

.accent { color: #22c55e; }
.font-mono { font-family: 'JetBrains Mono', monospace; }
</style>
