// template-5/src/components/sections/SkillsSection.tsx
'use client';

import { motion } from 'motion/react';
import ScrollReveal from '@/components/ui/scroll-reveal';
import ErrorBoundary from '@/components/ui/error-boundary';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Code2, Layout, Database, Brain, Wrench, Cloud } from 'lucide-react';
import portfolioData from '@/data/portfolio.json';

const skillCategories = [
  { label: 'Languages', icon: Code2, skills: portfolioData.skills.languages, color: 'text-blue-400' },
  { label: 'Frontend', icon: Layout, skills: portfolioData.skills.frontend, color: 'text-cyan-400' },
  { label: 'Backend', icon: Database, skills: portfolioData.skills.backend, color: 'text-orange-400' },
  { label: 'AI / ML', icon: Brain, skills: portfolioData.skills.ai, color: 'text-rose-400' },
  { label: 'Tools', icon: Wrench, skills: portfolioData.skills.tools, color: 'text-amber-400' },
  { label: 'Cloud', icon: Cloud, skills: portfolioData.skills.cloud, color: 'text-emerald-400' },
];

const allSkills = skillCategories.flatMap((cat) => cat.skills);

function MarqueeRow({ items, reverse = false }: { items: string[]; reverse?: boolean }) {
  return (
    <div className="relative overflow-hidden py-2">
      <div
        className={`flex gap-3 w-max ${reverse ? 'animate-marquee-reverse' : 'animate-marquee'}`}
      >
        {[...items, ...items].map((skill, i) => (
          <Badge
            key={`${skill}-${i}`}
            variant="secondary"
            className="whitespace-nowrap text-sm px-4 py-1.5 bg-primary/5 border-primary/20 text-muted-foreground hover:bg-primary/15 hover:text-primary transition-colors shrink-0"
          >
            {skill}
          </Badge>
        ))}
      </div>
    </div>
  );
}

export default function SkillsSection() {
  const mid = Math.ceil(allSkills.length / 2);
  const row1 = allSkills.slice(0, mid);
  const row2 = allSkills.slice(mid);

  return (
    <section id="skills" className="py-24 px-6 relative overflow-hidden">
      <div className="max-w-6xl mx-auto">
        <ErrorBoundary>
          <ScrollReveal direction="up">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Skills &amp; <span className="text-primary">Tech Stack</span>
            </h2>
            <div className="w-16 h-1 bg-primary rounded-full mb-8" />
          </ScrollReveal>
        </ErrorBoundary>

        <ErrorBoundary>
          <ScrollReveal direction="up" delay={0.1}>
            <div className="mb-12 space-y-1">
              <MarqueeRow items={row1} />
              <MarqueeRow items={row2} reverse />
            </div>
          </ScrollReveal>
        </ErrorBoundary>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {skillCategories.map((cat, i) => (
            <ErrorBoundary key={cat.label}>
              <ScrollReveal direction="up" delay={0.05 * i}>
                <motion.div
                  whileHover={{ y: -4, scale: 1.01 }}
                  transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                >
                  <Card className="group h-full border-border/50 bg-card/50 backdrop-blur-sm hover:border-primary/30 transition-all duration-300 hover:shadow-lg hover:shadow-primary/5">
                    <CardContent className="p-5">
                      <div className="flex items-center gap-2 mb-3">
                        <div className={`p-2 rounded-lg bg-primary/10 ${cat.color} group-hover:scale-110 transition-transform`}>
                          <cat.icon size={18} />
                        </div>
                        <span className="font-semibold group-hover:text-primary transition-colors">
                          {cat.label}
                        </span>
                      </div>
                      <div className="flex flex-wrap gap-1.5">
                        {cat.skills.map((skill) => (
                          <Badge
                            key={skill}
                            variant="secondary"
                            className="text-xs group-hover:bg-primary/10 group-hover:text-primary/80 transition-all"
                          >
                            {skill}
                          </Badge>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              </ScrollReveal>
            </ErrorBoundary>
          ))}
        </div>
      </div>
    </section>
  );
}

// template-5/src/components/SkillsSection.vue
<template>
  <section id="skills" class="section section-alt" style="overflow: hidden;">
    <div class="section-inner">
      <!-- Heading -->
      <div ref="headingRef" class="reveal">
        <SectionHeading first-word="My" second-word="Skills" />
      </div>

      <!-- Marquee rows -->
      <div ref="marqueeRef" class="reveal" style="transition-delay:0.1s; margin-bottom: 48px;">
        <div class="marquee-wrapper">
          <div class="marquee-track">
            <span v-for="(s, i) in doubleRow1" :key="'r1-' + i" class="skill-chip">{{ s }}</span>
          </div>
        </div>
        <div class="marquee-wrapper" style="margin-top: 8px;">
          <div class="marquee-track marquee-track--reverse">
            <span v-for="(s, i) in doubleRow2" :key="'r2-' + i" class="skill-chip">{{ s }}</span>
          </div>
        </div>
      </div>

      <!-- Category cards -->
      <div class="skills-grid">
        <div
          v-for="(cat, i) in skillCategories"
          :key="cat.label"
          class="reveal portfolio-card skill-card"
          :style="{ transitionDelay: `${i * 0.06}s` }"
          :ref="el => cardRefs[i] = el"
        >
          <div class="skill-card-header">
            <div class="skill-icon" :style="{ color: cat.color }">
              <v-icon :icon="cat.icon" size="20" />
            </div>
            <span class="skill-label">{{ cat.label }}</span>
          </div>
          <div class="skill-chips">
            <span v-for="skill in cat.skills" :key="skill" class="skill-chip skill-chip--sm">{{ skill }}</span>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { portfolio } from '@/data/portfolio.js'
import SectionHeading from '@/components/SectionHeading.vue'

const skillCategories = [
  { label: 'Languages', icon: 'mdi-code-tags',         color: '#60a5fa', skills: portfolio.skills.languages },
  { label: 'Frontend',  icon: 'mdi-monitor-screenshot', color: '#22d3ee', skills: portfolio.skills.frontend  },
  { label: 'Backend',   icon: 'mdi-database',            color: '#fb923c', skills: portfolio.skills.backend   },
  { label: 'AI / ML',   icon: 'mdi-brain',               color: '#f87171', skills: portfolio.skills.ai        },
  { label: 'Tools',     icon: 'mdi-tools',               color: '#fbbf24', skills: portfolio.skills.tools     },
  { label: 'Cloud',     icon: 'mdi-cloud-outline',        color: '#4ade80', skills: portfolio.skills.cloud     },
]

const allSkills  = skillCategories.flatMap(c => c.skills)
const mid        = Math.ceil(allSkills.length / 2)
const row1       = allSkills.slice(0, mid)
const row2       = allSkills.slice(mid)
const doubleRow1 = computed(() => [...row1, ...row1])
const doubleRow2 = computed(() => [...row2, ...row2])

const headingRef = ref(null)
const marqueeRef = ref(null)
const cardRefs   = ref([])

onMounted(() => {
  const observer = new IntersectionObserver(
    entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target) } }),
    { threshold: 0.1 }
  )
  const els = [headingRef.value, marqueeRef.value, ...cardRefs.value].filter(Boolean)
  els.forEach(el => observer.observe(el))
})
</script>

<style scoped>
.skills-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}

@media (max-width: 900px) { .skills-grid { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 550px) { .skills-grid { grid-template-columns: 1fr; } }

.skill-card { padding: 20px; cursor: default; }

.skill-card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 14px;
}

.skill-icon {
  width: 36px;
  height: 36px;
  border-radius: 8px;
  background: rgba(255,255,255,0.05);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  transition: transform 0.2s;
}

.skill-card:hover .skill-icon { transform: scale(1.1); }

.skill-label {
  font-weight: 600;
  font-size: 0.9375rem;
  color: #f4f4f5;
  transition: color 0.2s;
}

.skill-card:hover .skill-label { color: #22c55e; }

.skill-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.skill-chip--sm {
  font-size: 0.6875rem;
  padding: 3px 9px;
}

.accent { color: #22c55e; }
</style>
