// template-2/src/App.tsx
import HeroSection from './sections/HeroSection';
import MarqueeSection from './sections/MarqueeSection';
import AboutSection from './sections/AboutSection';
import CoursesSection from './sections/CoursesSection';
import ProjectsSection from './sections/ProjectsSection';
import ContactSection from './sections/ContactSection';

function App() {
  return (
    <main
      className="font-kanit"
      style={{ background: '#0C0C0C', overflowX: 'clip' }}
    >
      <HeroSection />
      <MarqueeSection />
      <AboutSection />
      <CoursesSection />
      <ProjectsSection />
      <ContactSection />
    </main>
  );
}

export default App;

// template-5/src/App.vue
<template>
  <v-app theme="dark">
    <AppNavbar />
    <v-main style="background: #0a0a0a; padding: 0;">
      <HeroSection />
      <AboutSection />
      <SkillsSection />
      <ProjectsSection />
      <CoursesSection />
      <EducationSection />
      <ContactSection />
      <AppFooter />
    </v-main>
  </v-app>
</template>

<script setup>
import AppNavbar from '@/components/AppNavbar.vue'
import HeroSection from '@/components/HeroSection.vue'
import AboutSection from '@/components/AboutSection.vue'
import SkillsSection from '@/components/SkillsSection.vue'
import ProjectsSection from '@/components/ProjectsSection.vue'
import CoursesSection from '@/components/CoursesSection.vue'
import EducationSection from '@/components/EducationSection.vue'
import ContactSection from '@/components/ContactSection.vue'
import AppFooter from '@/components/AppFooter.vue'
</script>
