// template-5/src/app/page.tsx
import Navbar from '@/components/sections/Navbar';
import HeroSection from '@/components/sections/HeroSection';
import AboutSection from '@/components/sections/AboutSection';
import SkillsSection from '@/components/sections/SkillsSection';
import ProjectsSection from '@/components/sections/ProjectsSection';
import CoursesSection from '@/components/sections/CoursesSection';
import EducationSection from '@/components/sections/EducationSection';
// import ExperienceSection from '@/components/sections/ExperienceSection';
import ContactSection from '@/components/sections/ContactSection';
import Footer from '@/components/sections/Footer';

export default function Home() {
  return (
    <main className="min-h-screen bg-background">
      <Navbar />
      <HeroSection />
      <AboutSection />
      <SkillsSection />
      <ProjectsSection />
      <CoursesSection />
      <EducationSection />
      {/* <ExperienceSection /> */}
      <ContactSection />
      <Footer />
    </main>
  );
}

// template-5/src/App.vue
<template>
  <v-app theme="dark">
    <AppNavbar />
    <v-main style="background: #0a0a0a; padding: 0;">
      <HeroSection />
      <AboutSection />
      <SkillsSection />
      <ProjectsSection />
      <CoursesSection />
      <EducationSection />
      <ContactSection />
      <AppFooter />
    </v-main>
  </v-app>
</template>

<script setup>
import AppNavbar from '@/components/AppNavbar.vue'
import HeroSection from '@/components/HeroSection.vue'
import AboutSection from '@/components/AboutSection.vue'
import SkillsSection from '@/components/SkillsSection.vue'
import ProjectsSection from '@/components/ProjectsSection.vue'
import CoursesSection from '@/components/CoursesSection.vue'
import EducationSection from '@/components/EducationSection.vue'
import ContactSection from '@/components/ContactSection.vue'
import AppFooter from '@/components/AppFooter.vue'
</script>
