// template-5/src/components/ContactSection.vue
<template>
  <section id="contact" class="section">
    <div class="section-inner--narrow" style="max-width: 860px; margin: 0 auto;">
      <!-- Heading -->
      <div ref="headingRef" class="reveal" style="text-align: center; margin-bottom: 12px;">
        <SectionHeading first-word="Contact" second-word="Me" :center="true" />
        <p class="contact-subtitle">
          Have a project in mind or want to collaborate? Feel free to reach out.
          I'm always open to discussing new opportunities and ideas.
        </p>
      </div>

      <!-- Two columns -->
      <div class="contact-grid">
        <!-- Info card -->
        <div ref="infoRef" class="reveal reveal--left glass-card contact-info" style="transition-delay:0.15s;">
          <div class="info-row">
            <div class="info-icon">
              <v-icon icon="mdi-email-outline" size="20" color="#22c55e" />
            </div>
            <div>
              <p class="info-label">Email</p>
              <a :href="`mailto:${portfolio.personal.email}`" class="info-value info-link">
                {{ portfolio.personal.email }}
              </a>
            </div>
          </div>

          <div class="info-row">
            <div class="info-icon">
              <v-icon icon="mdi-map-marker-outline" size="20" color="#22c55e" />
            </div>
            <div>
              <p class="info-label">Location</p>
              <p class="info-value">{{ portfolio.personal.location }}</p>
            </div>
          </div>

          <div class="info-row">
            <div class="info-icon">
              <v-icon icon="mdi-phone-outline" size="20" color="#22c55e" />
            </div>
            <div>
              <p class="info-label">Phone</p>
              <a :href="`tel:${portfolio.personal.phone}`" class="info-value info-link">
                {{ portfolio.personal.phone }}
              </a>
            </div>
          </div>

          <div class="info-divider" />
          <p class="info-label" style="margin-bottom: 14px;">Connect with me</p>
          <div class="contact-socials">
            <a
              v-for="s in socialLinks"
              :key="s.label"
              :href="s.href"
              :title="s.label"
              class="social-link"
              target="_blank"
              rel="noopener noreferrer"
            >
              <SocialIcon :icon="s.icon" :size="20" />
            </a>
          </div>
        </div>

        <!-- Form card -->
        <div ref="formRef" class="reveal reveal--right glass-card contact-form" style="transition-delay:0.3s;">
          <form :action="`mailto:${portfolio.personal.email}`" method="post" enctype="text/plain" @submit.prevent="submitForm">
            <div class="form-group">
              <label class="form-label" for="contact-name">Name</label>
              <input id="contact-name" v-model="form.name" name="name" type="text" class="form-input" placeholder="Your name" required />
            </div>
            <div class="form-group">
              <label class="form-label" for="contact-email">Email</label>
              <input id="contact-email" v-model="form.email" name="email" type="email" class="form-input" placeholder="your@email.com" required />
            </div>
            <div class="form-group">
              <label class="form-label" for="contact-message">Message</label>
              <textarea id="contact-message" v-model="form.message" name="message" class="form-input" placeholder="Your message..." rows="5" required />
            </div>

            <button type="submit" class="btn-primary" style="width: 100%; justify-content: center;">
              <v-icon icon="mdi-send" size="16" />
              Send Message
            </button>

            <p v-if="sent" class="form-success">
              <v-icon icon="mdi-check-circle-outline" size="16" color="#22c55e" />
              Message sent! Thank you for reaching out.
            </p>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { portfolio, socialLinks } from '@/data/portfolio.js'
import SocialIcon from '@/components/SocialIcon.vue'
import SectionHeading from '@/components/SectionHeading.vue'

const form = ref({ name: '', email: '', message: '' })
const sent = ref(false)

function submitForm() {
  const subject = encodeURIComponent(`Portfolio Contact from ${form.value.name}`)
  const body = encodeURIComponent(`Name: ${form.value.name}\nEmail: ${form.value.email}\n\n${form.value.message}`)
  window.location.href = `mailto:${portfolio.personal.email}?subject=${subject}&body=${body}`
  sent.value = true
  setTimeout(() => { sent.value = false }, 5000)
}

const headingRef = ref(null)
const infoRef    = ref(null)
const formRef    = ref(null)

onMounted(() => {
  const observer = new IntersectionObserver(
    entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target) } }),
    { threshold: 0.1 }
  )
  ;[headingRef.value, infoRef.value, formRef.value].filter(Boolean).forEach(el => observer.observe(el))
})
</script>

<style scoped>
.contact-subtitle {
  color: #71717a;
  max-width: 500px;
  margin: 0 auto 48px;
  line-height: 1.65;
}

.contact-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
  align-items: start;
}

@media (max-width: 700px) { .contact-grid { grid-template-columns: 1fr; } }

.contact-info, .contact-form {
  padding: 28px;
}

.info-row {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  margin-bottom: 20px;
  transition: transform 0.2s;
}
.info-row:hover { transform: translateX(4px); }

.info-icon {
  width: 40px;
  height: 40px;
  border-radius: 10px;
  background: rgba(34,197,94,0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.info-label { font-size: 0.75rem; color: #52525b; margin-bottom: 2px; }
.info-value { font-size: 0.875rem; color: #f4f4f5; }
.info-link  { text-decoration: none; transition: color 0.2s; }
.info-link:hover { color: #22c55e; }

.info-divider {
  border: none;
  border-top: 1px solid rgba(255,255,255,0.06);
  margin: 20px 0;
}

.contact-socials {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.form-group { margin-bottom: 16px; }

.form-success {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 12px;
  font-size: 0.8125rem;
  color: #22c55e;
}

.accent { color: #22c55e; }
</style>

// template-5/src/components/sections/ContactSection.tsx
'use client';

import { motion } from 'motion/react';
import ScrollReveal from '@/components/ui/scroll-reveal';
import ErrorBoundary from '@/components/ui/error-boundary';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Mail, MapPin, Send } from 'lucide-react';
import GithubIcon from '@/icons/github-icon';
import LinkedinIcon from '@/icons/linkedin-icon';
import TwitterXIcon from '@/icons/twitter-x-icon';
import InstagramIcon from '@/icons/instagram-icon';
import DiscordIcon from '@/icons/discord-icon';
import FacebookIcon from '@/icons/facebook-icon';
import portfolioData from '@/data/portfolio.json';

const socialLinks = [
  { icon: GithubIcon, href: portfolioData.personal.socials.github, label: 'GitHub' },
  { icon: LinkedinIcon, href: portfolioData.personal.socials.linkedin, label: 'LinkedIn' },
  { icon: TwitterXIcon, href: portfolioData.personal.socials.twitter, label: 'X / Twitter' },
  { icon: InstagramIcon, href: portfolioData.personal.socials.instagram, label: 'Instagram' },
  { icon: DiscordIcon, href: portfolioData.personal.socials.discord, label: 'Discord' },
  { icon: FacebookIcon, href: portfolioData.personal.socials.facebook, label: 'Facebook' },
];

export default function ContactSection() {
  return (
    <section id="contact" className="py-24 px-6 relative">
      <div className="max-w-4xl mx-auto">
        <ErrorBoundary>
          <ScrollReveal direction="up" className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Get In <span className="text-primary">Touch</span>
            </h2>
            <div className="w-16 h-1 bg-primary rounded-full mx-auto mb-6" />
            <p className="text-muted-foreground max-w-xl mx-auto">
              Have a project in mind or want to collaborate? Feel free to reach out.
              I&apos;m always open to discussing new opportunities and ideas.
            </p>
          </ScrollReveal>
        </ErrorBoundary>

        <div className="grid md:grid-cols-2 gap-6">
          <ErrorBoundary>
            <ScrollReveal direction="left" delay={0.2}>
              <Card className="border-border/50 bg-card/50 backdrop-blur-sm h-full hover:border-primary/30 transition-all duration-300">
                <CardContent className="p-6 space-y-6">
                  <motion.div
                    className="flex items-center gap-4"
                    whileHover={{ x: 4 }}
                    transition={{ type: 'spring', stiffness: 300 }}
                  >
                    <div className="p-3 rounded-lg bg-primary/10 text-primary">
                      <Mail size={20} />
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Email</p>
                      <a
                        href={`mailto:${portfolioData.personal.email}`}
                        className="hover:text-primary transition-colors"
                      >
                        {portfolioData.personal.email}
                      </a>
                    </div>
                  </motion.div>

                  <motion.div
                    className="flex items-center gap-4"
                    whileHover={{ x: 4 }}
                    transition={{ type: 'spring', stiffness: 300 }}
                  >
                    <div className="p-3 rounded-lg bg-primary/10 text-primary">
                      <MapPin size={20} />
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Location</p>
                      <p>{portfolioData.personal.location}</p>
                    </div>
                  </motion.div>

                  <div className="pt-4 border-t border-border/50">
                    <p className="text-sm text-muted-foreground mb-4">Connect with me</p>
                    <div className="flex items-center gap-4">
                      {socialLinks.map((social, i) => (
                        <motion.a
                          key={social.label}
                          href={social.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          title={social.label}
                          whileHover={{ scale: 1.2, y: -3 }}
                          whileTap={{ scale: 0.9 }}
                          initial={{ opacity: 0, y: 10 }}
                          whileInView={{ opacity: 1, y: 0 }}
                          viewport={{ once: true }}
                          transition={{ delay: 0.1 * i }}
                        >
                          <social.icon size={20} color="#a1a1aa" />
                        </motion.a>
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>
            </ScrollReveal>
          </ErrorBoundary>

          <ErrorBoundary>
            <ScrollReveal direction="right" delay={0.4}>
              <Card className="border-border/50 bg-card/50 backdrop-blur-sm h-full hover:border-primary/30 transition-all duration-300">
                <CardContent className="p-6">
                  <form
                    action={`mailto:${portfolioData.personal.email}`}
                    method="post"
                    encType="text/plain"
                    className="space-y-4"
                  >
                    <div>
                      <label htmlFor="name" className="text-sm text-muted-foreground mb-1 block">
                        Name
                      </label>
                      <motion.input
                        id="name"
                        name="name"
                        type="text"
                        className="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary transition-shadow hover:shadow-sm focus:shadow-md focus:shadow-primary/5"
                        placeholder="Your name"
                        whileFocus={{ scale: 1.01 }}
                      />
                    </div>
                    <div>
                      <label htmlFor="email" className="text-sm text-muted-foreground mb-1 block">
                        Email
                      </label>
                      <motion.input
                        id="email"
                        name="email"
                        type="email"
                        className="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary transition-shadow hover:shadow-sm focus:shadow-md focus:shadow-primary/5"
                        placeholder="your@email.com"
                        whileFocus={{ scale: 1.01 }}
                      />
                    </div>
                    <div>
                      <label htmlFor="message" className="text-sm text-muted-foreground mb-1 block">
                        Message
                      </label>
                      <motion.textarea
                        id="message"
                        name="message"
                        rows={4}
                        className="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary resize-none transition-shadow hover:shadow-sm focus:shadow-md focus:shadow-primary/5"
                        placeholder="Your message..."
                        whileFocus={{ scale: 1.01 }}
                      />
                    </div>
                    <motion.div whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                      <Button type="submit" className="w-full relative overflow-hidden group">
                        <span className="absolute inset-0 bg-gradient-to-r from-primary/0 via-white/10 to-primary/0 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-700" />
                        <Send size={16} className="relative z-10" />
                        <span className="relative z-10">Send Message</span>
                      </Button>
                    </motion.div>
                  </form>
                </CardContent>
              </Card>
            </ScrollReveal>
          </ErrorBoundary>
        </div>
      </div>
    </section>
  );
}
