// template-5/src/components/CoursesSection.vue
<template>
  <section id="courses" class="section section-alt" style="overflow: hidden; position: relative;">
    <!-- Dot grid background -->
    <div class="dot-bg" />

    <div class="section-inner" style="position: relative; z-index: 1;">
      <!-- Heading -->
      <div ref="headingRef" class="reveal">
        <SectionHeading first-word="Professional" second-word="Courses" />
      </div>

      <!-- Grid -->
      <div class="courses-grid">
        <a
          v-for="(course, i) in portfolio.courses"
          :key="course.platform"
          :href="course.link"
          target="_blank"
          rel="noopener noreferrer"
          class="reveal portfolio-card course-card"
          :style="{ transitionDelay: `${i * 0.06}s` }"
          :ref="el => cardRefs[i] = el"
        >
          <div class="course-header">
            <div class="course-icon" :style="iconStyle(course.platform)">
              <v-icon icon="mdi-certificate" size="20" />
            </div>
            <v-icon icon="mdi-open-in-new" size="16" class="course-ext-icon" />
          </div>
          <h3 class="course-platform">{{ course.platform }}</h3>
          <p class="course-description">{{ course.description }}</p>
        </a>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { portfolio } from '@/data/portfolio.js'
import SectionHeading from '@/components/SectionHeading.vue'

const platformColors = {
  'Coursera':          { color: '#60a5fa', background: 'rgba(96,165,250,0.12)'  },
  'Google Developers': { color: '#4ade80', background: 'rgba(74,222,128,0.12)'  },
  'Credly':            { color: '#fb923c', background: 'rgba(251,146,60,0.12)'  },
  'Microsoft Learn':   { color: '#38bdf8', background: 'rgba(56,189,248,0.12)'  },
  'Kaggle':            { color: '#22d3ee', background: 'rgba(34,211,238,0.12)'  },
  'HubSpot Academy':   { color: '#fbbf24', background: 'rgba(251,191,36,0.12)'  },
  'Anthropic':         { color: '#f87171', background: 'rgba(248,113,113,0.12)' },
  'LinkedIn Learning': { color: '#60a5fa', background: 'rgba(96,165,250,0.12)'  },
  'Forage':            { color: '#c084fc', background: 'rgba(192,132,252,0.12)' },
}

function iconStyle(platform) {
  return platformColors[platform] ?? { color: '#22c55e', background: 'rgba(34,197,94,0.1)' }
}

const headingRef = ref(null)
const cardRefs   = ref([])

onMounted(() => {
  const observer = new IntersectionObserver(
    entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target) } }),
    { threshold: 0.1 }
  )
  ;[headingRef.value, ...cardRefs.value].filter(Boolean).forEach(el => observer.observe(el))
})
</script>

<style scoped>
.courses-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}

@media (max-width: 900px) { .courses-grid { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 550px) { .courses-grid { grid-template-columns: 1fr; } }

.course-card {
  display: flex;
  flex-direction: column;
  padding: 20px;
  text-decoration: none;
  cursor: pointer;
}

.course-card:hover {
  border-color: rgba(34,197,94,0.35);
  box-shadow: 0 8px 32px rgba(34,197,94,0.08);
  transform: translateY(-4px) scale(1.005);
}

.course-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 14px;
}

.course-icon {
  width: 40px;
  height: 40px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(34,197,94,0.1);
  color: #22c55e;
  transition: transform 0.2s;
}
.course-icon .v-icon { color: inherit; }
.course-card:hover .course-icon { transform: scale(1.1); }

.course-ext-icon {
  color: #52525b;
  transition: color 0.2s, transform 0.2s;
}
.course-card:hover .course-ext-icon { color: #22c55e; transform: rotate(15deg); }

.course-platform {
  font-size: 0.9375rem;
  font-weight: 600;
  color: #f4f4f5;
  margin-bottom: 6px;
  transition: color 0.2s;
}
.course-card:hover .course-platform { color: #22c55e; }

.course-description {
  font-size: 0.8125rem;
  color: #71717a;
  line-height: 1.5;
}

.accent { color: #22c55e; }
</style>

// template-5/src/components/sections/CoursesSection.tsx
'use client';

import { motion } from 'motion/react';
import ScrollReveal from '@/components/ui/scroll-reveal';
import ErrorBoundary from '@/components/ui/error-boundary';
import GridBackground from '@/components/ui/grid-background';
import { Card, CardContent } from '@/components/ui/card';
import { ExternalLink, Award } from 'lucide-react';
import portfolioData from '@/data/portfolio.json';

const platformColors: Record<string, string> = {
  Coursera: 'bg-blue-500/10 text-blue-400',
  'Google Developers': 'bg-green-500/10 text-green-400',
  Credly: 'bg-orange-500/10 text-orange-400',
  'Microsoft Learn': 'bg-sky-500/10 text-sky-400',
  Kaggle: 'bg-cyan-500/10 text-cyan-400',
  'HubSpot Academy': 'bg-amber-500/10 text-amber-400',
  Anthropic: 'bg-rose-500/10 text-rose-400',
  'LinkedIn Learning': 'bg-blue-600/10 text-blue-400',
  Forage: 'bg-purple-500/10 text-purple-400',
};

export default function CoursesSection() {
  return (
    <section id="courses" className="py-24 px-6 bg-secondary/30 relative overflow-hidden">
      <GridBackground dotColor="rgba(34, 197, 94, 0.08)" spacing={50} dotSize={1} />

      <div className="max-w-6xl mx-auto relative z-10">
        <ErrorBoundary>
          <ScrollReveal direction="up">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Courses &amp; <span className="text-primary">Certifications</span>
            </h2>
            <div className="w-16 h-1 bg-primary rounded-full mb-8" />
          </ScrollReveal>
        </ErrorBoundary>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {portfolioData.courses.map((course, i) => (
            <ErrorBoundary key={course.platform}>
              <ScrollReveal direction="up" delay={0.05 * i}>
                <motion.div
                  whileHover={{ y: -4, scale: 1.01 }}
                  transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                >
                  <Card className="group h-full border-border/50 bg-card/50 backdrop-blur-sm hover:border-primary/30 transition-all duration-300 hover:shadow-lg hover:shadow-primary/5">
                    <CardContent className="p-5">
                      <div className="flex items-start justify-between mb-3">
                        <div className={`p-2 rounded-lg ${platformColors[course.platform] || 'bg-primary/10 text-primary'} group-hover:scale-110 transition-transform`}>
                          <Award size={18} />
                        </div>
                        <motion.a
                          href={course.link}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center justify-center h-8 w-8 rounded-md text-muted-foreground hover:text-primary hover:bg-accent transition-colors"
                          whileHover={{ scale: 1.1, rotate: 15 }}
                          whileTap={{ scale: 0.9 }}
                        >
                          <ExternalLink size={14} />
                        </motion.a>
                      </div>

                      <h3 className="font-semibold mb-1 group-hover:text-primary transition-colors">
                        {course.platform}
                      </h3>
                      <p className="text-sm text-muted-foreground">
                        {course.description}
                      </p>
                    </CardContent>
                  </Card>
                </motion.div>
              </ScrollReveal>
            </ErrorBoundary>
          ))}
        </div>
      </div>
    </section>
  );
}
